
DROP SEQUENCE MYSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYSEQ;

--번호(MYNO), 작성자(MYNAME), 제목(MYTITLE), 내용(MYCONTENT), 날짜(MYDATE) 
CREATE TABLE MYBOARD(
MYNO NUMBER PRIMARY KEY,
MYNAME VARCHAR2(50) NOT NULL,
MYTITLE VARCHAR2(2000) NOT NULL,
MYCONTENT VARCHAR2(4000) NOT NULL,
MYDATE DATE NOT NULL
);

SELECT * FROM MYBOARD;

INSERT INTO MYBOARD VALUES(MYSEQ.NEXTVAL,'관리자','테스트중입니다.','TEST CONTENT',SYSDATE);